import argparse
import sys
import time

# This module is auto-generated by UniFFI
try:
    import po
except ImportError:
    print("Error: Could not import 'po'. Have you run 'cargo run --bin uniffi-bindgen generate'?")
    sys.exit(1)

def run_server(port):
    print(f"🚀 [Server] Binding to port {port}...")
    try:
        server = po.PoClient(str(port), None)
        print(f"   [Server] Node ID: {server.node_id()}")
        
        while True:
            print("   [Server] Waiting for data from peer...")
            data = server.recv()
            if data:
                print(f"   [Server] Received (encrypted): {bytes(data).decode('utf-8')}")
                server.send(b"Message received loud and clear!")
            time.sleep(1)
            
    except po.PoFfiError as e:
         print(f"Server error: {e}")

def run_client(port):
    print(f"🚀 [Client] Connecting to 127.0.0.1:{port}...")
    try:
        client = po.PoClient("0", f"127.0.0.1:{port}")
        print(f"   [Client] Node ID: {client.node_id()}")
        
        msg = b"Hello from Python land via E2EE QUIC!"
        print(f"   [Client] Sending: {msg.decode('utf-8')}")
        client.send(msg)
        
        print("   [Client] Waiting for reply...")
        reply = client.recv()
        if reply:
            print(f"   [Client] Received reply: {bytes(reply).decode('utf-8')}")
        
    except po.PoFfiError as e:
         print(f"Client error: {e}")

import threading

if __name__ == "__main__":
    print("🚀 Starting Protocol Orzatty Python Binding Test\n")
    port = 5545
    
    server_thread = threading.Thread(target=run_server, args=(port,), daemon=True)
    server_thread.start()
    
    time.sleep(0.5) # Wait for server to bind
    run_client(port)
    
    print("\n✅ Python Bindings test passed!")
