/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class PoClient {
  /** Bind to a local port to accept incoming connections. */
  static bind(port: number): Promise<PoClient>
  /** Connect to a remote PO node. */
  static connect(address: string): Promise<PoClient>
  /** Get the cryptographic Node ID of this client. */
  get nodeId(): string
  /** Send a Buffer of data to the peer. */
  send(data: Buffer): Promise<void>
  /**
   * Receive a Buffer of data from the peer.
   * Returns undefined if the stream is closed gracefully.
   */
  recv(): Promise<Buffer | null>
  /** Gracefully close the connection. */
  close(): Promise<void>
}
